# Generated by Django 5.0.3 on 2024-03-22 06:27

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faceRecon", "0002_alter_studentmodel_img_encoded"),
    ]

    operations = [
        migrations.CreateModel(
            name="staffModel",
            fields=[
                ("studentName", models.CharField(max_length=50)),
                ("username", models.BigAutoField(primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("collegeName", models.CharField(max_length=100)),
                ("dept", models.CharField(max_length=50)),
                ("year", models.CharField(max_length=10)),
                ("mobile", models.BigIntegerField()),
                ("addr", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=20)),
                (
                    "name_slug",
                    autoslug.fields.AutoSlugField(
                        default=None,
                        editable=False,
                        null=True,
                        populate_from="studentName",
                        unique=True,
                    ),
                ),
                ("img", models.FileField(upload_to="studentImg/")),
                ("img_encoded", models.BinaryField(null=True)),
            ],
        ),
    ]
