# Generated by Django 5.0.3 on 2024-03-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faceRecon", "0004_rename_studentname_staffmodel_staffname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmodel",
            name="img_encoded",
            field=models.BinaryField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="staffmodel",
            name="staffName",
            field=models.CharField(max_length=100),
        ),
    ]
