# Generated by Django 5.0.3 on 2024-04-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faceRecon", "0005_alter_staffmodel_img_encoded_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmodel",
            name="img_encoded",
            field=models.BinaryField(null=True, unique=True),
        ),
    ]
